# Base image name alpine
FROM node:alpine        
# specify the root directory
WORKDIR '/app'
# copying package.json file to root directory
COPY package.json .
# run npm install to install necessary dependencies from package.json
RUN npm install
# copy everything for docker cache layer
COPY . .
# default command for this Image
CMD ["npm", "run", "start"]