version: "3.8"

services:
  frontend:
    container_name: git_dashboard_container
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
    